name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement']
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Is your feature request related to a problem?
        Describe the problem you're trying to solve.

        ## Describe the solution you'd like
        What would you like to happen?

        ## Describe alternatives you've considered
        What alternatives have you considered?

        ## Additional Context
        Add any other context or screenshots about the feature request here.
